import Sidebar from "../components/Sidebar";

export const metadata = {
  title: 'Startex Hub | Businessman Services',
  description: 'Generated by create next app',
};

export default function AdminLayout({ children }) {
  return (
    <div className="flex flex-col md:flex-row antialiased text-white min-h-screen">
      {/* Sidebar (fixed) */}
      <Sidebar />

      {/* Main content */}
      <main className="flex-1 pt-2 px-4 md:ml-64 transition-all duration-300">
        {children}
      </main>
    </div>
  );
}


